### PR TITLE
add remove

### LINKED ISSUE #20: Remove from array
Following the instruction, we can add to the array. But I could not find a way how to remove an element from array. 

```
// push stuff to an array for a particular key
    await db.push("transformers", "optimus prime");
    await db.push("transformers", "bumblebee");
    await db.push("transformers", "iron hide");

```

### PR DESCRIPTION
**Pull request by wh0**
fixes #20

### CODE REVIEW

**Review by khalby786 — DISMISSED** [review]
Can you update the tests by following suit with the rest of the tests in `tests/test.js` [because it was recently updated in a previous commit](https://github.com/khalby786/jsoning/blob/3467081fa0886c3c5146c16ba6dff42bb8612f57/tests/test.js)?

Particularly the part where I create a new instance of Jsoning for each test case for successful results. 😆 

I will be fixing it like how @javaarchive mention in https://github.com/khalby786/jsoning/issues/25#issuecomment-932792176. But until, then for consistency, I'd like you to update the tests!

**Comment by khalby786** [comment]
As for the conflict, I will fix it while merging.

**Comment by wh0** [comment]
thanks for reviewing. I'll see if I can update the tests tonight.

**Comment by wh0** [comment]
ok I've rebased this and updated the tests

be aware, the tests now fail with

```
rm: cannot remove '*.test.json': No such file or directory
```

this seems like an issue in master though

**Review by khalby786 — APPROVED** [review]
LGTM.

**Comment by khalby786** [comment]
@all-contributors please add @wh0 for code

**Pull request merged**
